# Generated by Django 5.1.1 on 2024-09-18 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordenes',
            },
        ),
        migrations.CreateModel(
            name='OrdenDetailModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_detail', to='almacen.productosmodel')),
                ('orden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_detail', to='transacciones.ordenesmodel')),
            ],
            options={
                'db_table': 'orden_detail',
            },
        ),
        migrations.CreateModel(
            name='PagosModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.FloatField()),
                ('metodo_pago', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta')], max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('orden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='transacciones.ordenesmodel')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
    ]
