# Generated by Django 5.1.1 on 2024-09-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosmodel',
            name='imagen_url_full',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productosmodel',
            name='imagen_url',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
